<a href="https://colab.research.google.com/github/ylmgrbzz/E-Commerce-Purchases-Data-Analysis-with-Pandas/blob/main/E-Commerce%20Purchases%20Data%20Analysis%20with%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
data= pd.read_csv("Ecommerce Purchases")
data

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

In [4]:
data.head(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63

In [5]:
data.tail(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9990,"75731 Molly Springs\nWest Danielle, VT 96934-5102",93 ty,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4;...,"Pace, Vazquez and Richards",869968197049750,04/24,877,JCB 15 digit,andersonmichael@sherman.biz,Early years teacher,54.170.3.185,ru,18.35
9991,"PSC 8165, Box 8498\nAPO AP 60327-0346",50 dA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Snyder Inc,4221582137197481,02/24,969,Voyager,kking@wise-liu.com,IT sales professional,254.25.31.156,el,25.93
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

In [6]:
data.dtypes

Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card           int64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

In [8]:
data.isnull().sum()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

In [9]:
len(data.columns)

14

In [11]:
data["Purchase Price"].max()

99.99

In [12]:
data["Purchase Price"].min()

0.0

In [13]:
data["Purchase Price"].mean()

50.347302

In [15]:
data["Language"]

0       el
1       fr
2       de
3       es
4       es
        ..
9995    it
9996    pt
9997    el
9998    es
9999    el
Name: Language, Length: 10000, dtype: object

In [18]:
len(data[data["Language"]=="fr"])

1097

In [19]:
data["Job"]

0       Scientist, product/process development
1                            Drilling engineer
2                     Customer service manager
3                            Drilling engineer
4                                  Fine artist
                         ...
9995                                Printmaker
9996                           Energy engineer
9997                        Veterinary surgeon
9998                  Local government officer
9999                    Embryologist, clinical
Name: Job, Length: 10000, dtype: object

In [21]:
data[data["Job"].str.contains("engineer",case=False)]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
50,"41159 Michael Centers\nAdamsfort, RI 37108-6674",46 Ce,PM,Mozilla/5.0 (Windows 98; Win 9x 4.90; sl-SI; r...,"Wright, Williams and Mendez",4008586485908075,05/19,945,JCB 16 digit,susanvalentine@obrien.org,Mechanical engineer,213.203.143.215,de,36.85
55,"27635 Maureen Bypass Apt. 883\nSandraview, SD ...",59 LJ,AM,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_3 like M...,Sims-Lyons,3158113629128344,09/19,857,VISA 16 digit,adkinsarthur@yahoo.com,"Engineer, broadcasting (operations)",227.235.89.210,pt,48.74
60,"7126 Katherine Squares\nPerkinsview, CO 97299-...",63 qu,AM,Opera/8.68.(X11; Linux x86_64; en-US) Presto/2...,Marshall-Fernandez,349767747049645,05/20,672,JCB 15 digit,sweeneyhannah@jones.biz,"Engineer, agricultural",197.144.142.102,de,20.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9948,"95544 Johnson Isle Suite 939\nMichaelberg, RI ...",91 bW,AM,Opera/8.36.(X11; Linux x86_64; sl-SI) Presto/2...,Fox-Peterson,4762924304307,03/17,567,Mastercard,haleybenjamin@gmail.com,Structural engineer,120.36.140.58,en,71.89
9952,"9991 Vaughn Hills\nRacheltown, PA 55409",36 KC,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,"Ward, Smith and Castillo",6011679271321726,09/19,964,Voyager,jonesjennifer@olson.com,"Engineer, energy",116.228.12.42,es,39.63
9970,"0060 Keith Stream\nWestport, CO 47097",11 nt,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,"Carpenter, Good and Hart",6011485664704662,07/19,543,Discover,rangelbrian@hotmail.com,Electrical engineer,242.8.85.205,en,17.76
9977,"02182 Keith Expressway\nEast Shannon, CT 20578...",34 RL,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Deleon, Jacobson and Benton",4186094003664688,06/21,397,JCB 16 digit,daltoncarter@yahoo.com,Biomedical engineer,146.238.118.2,fr,94.93
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63

In [22]:
len(data[data["Job"].str.contains("engineer",case=False)])

984

In [28]:
data[data["IP Address"]=="15.160.41.51"]["Email"]

1    anthony41@reed.com
Name: Email, dtype: object

In [29]:
data[(data["CC Provider"]=="Mastercard") & (data["Purchase Price"]>50)]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
18,"461 Christopher Square\nWest Michaelchester, C...",17 SB,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Beard, Abbott and Pena",6011350184276270,12/22,767,Mastercard,hannah63@yahoo.com,Photographer,73.250.176.201,el,70.15
31,USNS Alvarado\nFPO AA 27052-1231,26 Lh,PM,Opera/8.84.(X11; Linux i686; sl-SI) Presto/2.9...,Nicholson Group,4614997834548,03/22,909,Mastercard,ashley12@hotmail.com,Sales executive,94.176.142.201,en,94.14
35,"93392 Webb Gardens Apt. 220\nLaurabury, AR 999...",37 om,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Mora Ltd,6011049630969815,09/16,367,Mastercard,hgonzalez@mcdowell.com,"Lecturer, further education",216.23.95.40,zh,97.46
90,"431 Bowen Lights\nFergusonborough, MH 01362",31 tG,AM,Mozilla/5.0 (Windows NT 5.2; it-IT; rv:1.9.1.2...,Copeland-Lee,639032576097,06/18,868,Mastercard,nrogers@brown.com,"Teacher, English as a foreign language",153.188.13.203,es,78.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9941,"43757 Brown Lodge\nValerieberg, PR 88518",68 DG,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,"Jones, Williams and Dunn",6011508474487291,04/26,906,Mastercard,christian55@gmail.com,Secondary school teacher,216.118.235.145,fr,60.03
9948,"95544 Johnson Isle Suite 939\nMichaelberg, RI ...",91 bW,AM,Opera/8.36.(X11; Linux x86_64; sl-SI) Presto/2...,Fox-Peterson,4762924304307,03/17,567,Mastercard,haleybenjamin@gmail.com,Structural engineer,120.36.140.58,en,71.89
9954,"051 Samantha Wells Apt. 328\nScottborough, OR ...",11 vG,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_2...,"Mendoza, Zimmerman and Reilly",30232295374907,05/21,762,Mastercard,brownamy@perkins.com,"Presenter, broadcasting",61.97.84.101,it,87.15
9981,"087 Larson Roads Apt. 587\nRicestad, WI 98077-...",95 Kw,AM,Opera/9.63.(Windows NT 5.01; en-US) Presto/2.9...,"Ortiz, Schultz and Adams",4690863684605,01/19,695,Mastercard,laurenbennett@richards.com,Environmental education officer,106.21.237.73,pt,63.61
9987,"2754 Klein Mission\nJohnsonview, PA 64925-9624",65 Fg,PM,Opera/9.26.(Windows CE; sl-SI) Presto/2.9.188 ...,Curtis LLC,180027305702263,12/24,865,Mastercard,denisehamilton@novak.biz,Primary school teacher,164.39.190.217,es,60.83

In [30]:
len(data[(data["CC Provider"]=="Mastercard") & (data["Purchase Price"]>50)])

405

In [32]:
data["CC Exp Date"]

0       02/20
1       11/18
2       08/19
3       02/24
4       10/25
        ...
9995    03/22
9996    07/25
9997    05/21
9998    11/17
9999    02/19
Name: CC Exp Date, Length: 10000, dtype: object

In [37]:
def fun():
  count=0
  for date in data ["CC Exp Date"]:
    if date.split('/')[1]=='20':
      count=count+1
  print(count)

In [38]:
fun()

988

In [39]:
len(data[data["CC Exp Date"].apply(lambda x:x[3:]=="20")])

988

In [42]:
data["Email"].head(3)

0                 pdunlap@yahoo.com
1                anthony41@reed.com
2    amymiller@morales-harrison.com
Name: Email, dtype: object

In [41]:
lista=[]
for email in data["Email"]:
  lista.append(email.split('@')[1])

In [43]:
data["temp"]=lista

In [44]:
data.head(2)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,temp
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,yahoo.com
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73,reed.com

In [45]:
data["temp"].value_counts().head()

hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: temp, dtype: int64

In [50]:
data["Email"].apply(lambda x:x.split("@")[1]).value_counts().head()

hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: Email, dtype: int64